name: shelf_plus
description: Shelf Plus is a quality of life addon for your server-side development within the Shelf platform.
version: 1.10.0
repository: https://github.com/felixblaschke/shelf_plus

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf_hotreload: ^1.5.0
  shelf_web_socket: ^2.0.0
  mime_type: ^1.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.2
  dio: ^5.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
