name: shelf_plus
description: Shelf Plus is a quality of life addon for your server-side development within the Shelf platform.
version: 1.3.0
repository: https://github.com/felixblaschke/shelf_plus

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  shelf_hotreload: ^1.3.0
  shelf_web_socket: ^1.0.2
  mime_type: ^1.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
  dio: ^4.0.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  build_runner: ^2.0.1
