name: example_rest
description: Shelf Plus Example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf_plus:
    path: ../../
  json_annotation: ^4.0.1
  uuid: 3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  json_serializable: ^4.1.1
  build_runner: ^2.0.1
