name: example_rest
description: Shelf Plus Example

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  shelf_plus:
    path: ../../
  json_annotation: ^4.9.0
  uuid: 4.5.1

dev_dependencies:
  lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
